// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx

import (
    `unsafe`
)

//go:nosplit
//go:noescape
//goland:noinspection ALL
func ___asm2asm_compiled_code__DO_NOT_CALL_THIS_SYMBOL___()

var (
    _func__base        = ___asm2asm_compiled_code__DO_NOT_CALL_THIS_SYMBOL___
    _subr__f64toa      = **(**uintptr)(unsafe.Pointer(&_func__base)) + 3108
    _subr__i64toa      = **(**uintptr)(unsafe.Pointer(&_func__base)) + 6165
    _subr__lquote      = **(**uintptr)(unsafe.Pointer(&_func__base)) + 941
    _subr__lspace      = **(**uintptr)(unsafe.Pointer(&_func__base)) + 1583
    _subr__lzero       = **(**uintptr)(unsafe.Pointer(&_func__base)) + 0
    _subr__search      = **(**uintptr)(unsafe.Pointer(&_func__base)) + 16907
    _subr__skip_array  = **(**uintptr)(unsafe.Pointer(&_func__base)) + 14640
    _subr__skip_object = **(**uintptr)(unsafe.Pointer(&_func__base)) + 14675
    _subr__skip_one    = **(**uintptr)(unsafe.Pointer(&_func__base)) + 13010
    _subr__u64toa      = **(**uintptr)(unsafe.Pointer(&_func__base)) + 6258
    _subr__unquote     = **(**uintptr)(unsafe.Pointer(&_func__base)) + 7446
    _subr__value       = **(**uintptr)(unsafe.Pointer(&_func__base)) + 9078
    _subr__vnumber     = **(**uintptr)(unsafe.Pointer(&_func__base)) + 11518
    _subr__vsigned     = **(**uintptr)(unsafe.Pointer(&_func__base)) + 12482
    _subr__vstring     = **(**uintptr)(unsafe.Pointer(&_func__base)) + 10190
    _subr__vunsigned   = **(**uintptr)(unsafe.Pointer(&_func__base)) + 12741
)

var (
    _ = _subr__f64toa
    _ = _subr__i64toa
    _ = _subr__lquote
    _ = _subr__lspace
    _ = _subr__lzero
    _ = _subr__search
    _ = _subr__skip_array
    _ = _subr__skip_object
    _ = _subr__skip_one
    _ = _subr__u64toa
    _ = _subr__unquote
    _ = _subr__value
    _ = _subr__vnumber
    _ = _subr__vsigned
    _ = _subr__vstring
    _ = _subr__vunsigned
)
