name: Push Check Linux-ARM

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x, 1.20.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clear repository
        run: sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: main
        run: GOMAXPROCS=4 go test -v -race github.com/bytedance/sonic

      - name: ast
        run: GOMAXPROCS=4 go test -v -race github.com/bytedance/sonic/ast

      - name: external
        run: |
          cd ./external_jsonlib_test
          GOMAXPROCS=4 go test -v -race ./...
